apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: deployment
    
spec: 
  template:
    metadata:
      name: myapp-pod
      labels:
        app: webapp
        tier: front-end
    spec: 
      containers:
      - name: webapp
        image: ezikov/webapp:version1
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      tier: front-end

  
    