apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: default
  labels:
    app: nginx
    tier: front-end

spec: 
  containers:
    - name: nginx-container
      image: nginx
    
      resources:
        requests:
          memory: "1Gi"
          cpu: 1

        limits:
          memory: "2Gi"
          cpu: 2
  
    