apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: default
  labels:
    app: nginx
    tier: front-end

spec: 
  containers:
    - name: nginx-container
      image: nginx
      

  
    