apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: replicationcontroller
    
spec: 
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
        tier: front-end
    spec: 
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
 
  
    