apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: replicaset
    
spec: 
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
        tier: front-end
    spec: 
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: front-end

  
    